/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MobileVersion'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MobileVersion'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ApplicationVersionCreate = factory(root.LifetimeSdk.ApiClient, root.LifetimeSdk.MobileVersion);
  }
}(this, function(ApiClient, MobileVersion) {
  'use strict';




  /**
   * The ApplicationVersionCreate model module.
   * @module model/ApplicationVersionCreate
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ApplicationVersionCreate</code>.
   * A structure holding the new version name for the application and for its native applications, if applicable.
   * @alias module:model/ApplicationVersionCreate
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ApplicationVersionCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationVersionCreate} obj Optional instance to populate.
   * @return {module:model/ApplicationVersionCreate} The populated <code>ApplicationVersionCreate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ChangeLog')) {
        obj['ChangeLog'] = ApiClient.convertToType(data['ChangeLog'], 'String');
      }
      if (data.hasOwnProperty('Version')) {
        obj['Version'] = ApiClient.convertToType(data['Version'], 'String');
      }
      if (data.hasOwnProperty('MobileVersions')) {
        obj['MobileVersions'] = ApiClient.convertToType(data['MobileVersions'], [MobileVersion]);
      }
      if (data.hasOwnProperty('ModuleVersionKeys')) {
        obj['ModuleVersionKeys'] = ApiClient.convertToType(data['ModuleVersionKeys'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Change log of the version to be created.
   * @member {String} ChangeLog
   * @default ''
   */
  exports.prototype['ChangeLog'] = '';
  /**
   * Version of the application.
   * @member {String} Version
   * @default ''
   */
  exports.prototype['Version'] = '';
  /**
   * List of mobile versions.
   * @member {Array.<module:model/MobileVersion>} MobileVersions
   */
  exports.prototype['MobileVersions'] = undefined;
  /**
   * List of module version keys to validate if the current state of the application is still the expected.
   * @member {Array.<String>} ModuleVersionKeys
   */
  exports.prototype['ModuleVersionKeys'] = undefined;



  return exports;
}));


