/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ApplicationVersionKeyRecord = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApplicationVersionKeyRecord model module.
   * @module model/ApplicationVersionKeyRecord
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ApplicationVersionKeyRecord</code>.
   * 
   * @alias module:model/ApplicationVersionKeyRecord
   * @class
   * @param applicationVersionKey {String} The key of the newly created application version.
   */
  var exports = function(applicationVersionKey) {
    var _this = this;

    _this['ApplicationVersionKey'] = applicationVersionKey;
  };

  /**
   * Constructs a <code>ApplicationVersionKeyRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationVersionKeyRecord} obj Optional instance to populate.
   * @return {module:model/ApplicationVersionKeyRecord} The populated <code>ApplicationVersionKeyRecord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ApplicationVersionKey')) {
        obj['ApplicationVersionKey'] = ApiClient.convertToType(data['ApplicationVersionKey'], 'String');
      }
    }
    return obj;
  }

  /**
   * The key of the newly created application version.
   * @member {String} ApplicationVersionKey
   * @default ''
   */
  exports.prototype['ApplicationVersionKey'] = '';



  return exports;
}));


