/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApplicationOperation', 'model/ModuleConflict'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApplicationOperation'), require('./ModuleConflict'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ApplicationConflict = factory(root.LifetimeSdk.ApiClient, root.LifetimeSdk.ApplicationOperation, root.LifetimeSdk.ModuleConflict);
  }
}(this, function(ApiClient, ApplicationOperation, ModuleConflict) {
  'use strict';




  /**
   * The ApplicationConflict model module.
   * @module model/ApplicationConflict
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ApplicationConflict</code>.
   * A depoyment conflict.
   * @alias module:model/ApplicationConflict
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ApplicationConflict</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationConflict} obj Optional instance to populate.
   * @return {module:model/ApplicationConflict} The populated <code>ApplicationConflict</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Message')) {
        obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
      }
      if (data.hasOwnProperty('ProducerApplicationOperation')) {
        obj['ProducerApplicationOperation'] = ApplicationOperation.constructFromObject(data['ProducerApplicationOperation']);
      }
      if (data.hasOwnProperty('ConsumerApplicationOperation')) {
        obj['ConsumerApplicationOperation'] = ApplicationOperation.constructFromObject(data['ConsumerApplicationOperation']);
      }
      if (data.hasOwnProperty('ModuleConflict')) {
        obj['ModuleConflict'] = ModuleConflict.constructFromObject(data['ModuleConflict']);
      }
    }
    return obj;
  }

  /**
   * Description of the conflict.
   * @member {String} Message
   * @default ''
   */
  exports.prototype['Message'] = '';
  /**
   * @member {module:model/ApplicationOperation} ProducerApplicationOperation
   */
  exports.prototype['ProducerApplicationOperation'] = undefined;
  /**
   * @member {module:model/ApplicationOperation} ConsumerApplicationOperation
   */
  exports.prototype['ConsumerApplicationOperation'] = undefined;
  /**
   * @member {module:model/ModuleConflict} ModuleConflict
   */
  exports.prototype['ModuleConflict'] = undefined;



  return exports;
}));


