/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ApplicationOperation = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ApplicationOperation model module.
   * @module model/ApplicationOperation
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ApplicationOperation</code>.
   * Operation executed in the deployment over the application.
   * @alias module:model/ApplicationOperation
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ApplicationOperation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationOperation} obj Optional instance to populate.
   * @return {module:model/ApplicationOperation} The populated <code>ApplicationOperation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ApplicationKey')) {
        obj['ApplicationKey'] = ApiClient.convertToType(data['ApplicationKey'], 'String');
      }
      if (data.hasOwnProperty('ApplicationVersionKey')) {
        obj['ApplicationVersionKey'] = ApiClient.convertToType(data['ApplicationVersionKey'], 'String');
      }
      if (data.hasOwnProperty('DeploymentOperation')) {
        obj['DeploymentOperation'] = ApiClient.convertToType(data['DeploymentOperation'], 'String');
      }
    }
    return obj;
  }

  /**
   * Application unique identifier.
   * @member {String} ApplicationKey
   * @default ''
   */
  exports.prototype['ApplicationKey'] = '';
  /**
   * Application Version unique identifier.
   * @member {String} ApplicationVersionKey
   * @default ''
   */
  exports.prototype['ApplicationVersionKey'] = '';
  /**
   * Label of the operation to be performed. Example: Deploy 1.5.
   * @member {String} DeploymentOperation
   * @default ''
   */
  exports.prototype['DeploymentOperation'] = '';



  return exports;
}));


