/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MobileAppStatusInEnv', 'model/ModuleStatusInEnv'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MobileAppStatusInEnv'), require('./ModuleStatusInEnv'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.AppStatusInEnv = factory(root.LifetimeSdk.ApiClient, root.LifetimeSdk.MobileAppStatusInEnv, root.LifetimeSdk.ModuleStatusInEnv);
  }
}(this, function(ApiClient, MobileAppStatusInEnv, ModuleStatusInEnv) {
  'use strict';




  /**
   * The AppStatusInEnv model module.
   * @module model/AppStatusInEnv
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>AppStatusInEnv</code>.
   * Status of application in a given environment.
   * @alias module:model/AppStatusInEnv
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>AppStatusInEnv</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AppStatusInEnv} obj Optional instance to populate.
   * @return {module:model/AppStatusInEnv} The populated <code>AppStatusInEnv</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('EnvironmentKey')) {
        obj['EnvironmentKey'] = ApiClient.convertToType(data['EnvironmentKey'], 'String');
      }
      if (data.hasOwnProperty('BaseApplicationVersionKey')) {
        obj['BaseApplicationVersionKey'] = ApiClient.convertToType(data['BaseApplicationVersionKey'], 'String');
      }
      if (data.hasOwnProperty('IsModified')) {
        obj['IsModified'] = ApiClient.convertToType(data['IsModified'], 'Boolean');
      }
      if (data.hasOwnProperty('IsModifiedReason')) {
        obj['IsModifiedReason'] = ApiClient.convertToType(data['IsModifiedReason'], 'String');
      }
      if (data.hasOwnProperty('IsModifiedMessage')) {
        obj['IsModifiedMessage'] = ApiClient.convertToType(data['IsModifiedMessage'], 'String');
      }
      if (data.hasOwnProperty('ConsistencyStatus')) {
        obj['ConsistencyStatus'] = ApiClient.convertToType(data['ConsistencyStatus'], 'String');
      }
      if (data.hasOwnProperty('ConsistencyStatusMessages')) {
        obj['ConsistencyStatusMessages'] = ApiClient.convertToType(data['ConsistencyStatusMessages'], 'String');
      }
      if (data.hasOwnProperty('MobileAppsStatus')) {
        obj['MobileAppsStatus'] = ApiClient.convertToType(data['MobileAppsStatus'], [MobileAppStatusInEnv]);
      }
      if (data.hasOwnProperty('ModuleStatusInEnvs')) {
        obj['ModuleStatusInEnvs'] = ApiClient.convertToType(data['ModuleStatusInEnvs'], [ModuleStatusInEnv]);
      }
    }
    return obj;
  }

  /**
   * Environment unique identifier.
   * @member {String} EnvironmentKey
   * @default ''
   */
  exports.prototype['EnvironmentKey'] = '';
  /**
   * Base application version unique identifier. If app is not modified in environment, this is the application version deployed.
   * @member {String} BaseApplicationVersionKey
   * @default ''
   */
  exports.prototype['BaseApplicationVersionKey'] = '';
  /**
   * True if the application has been changed since the last tag, false otherwise.
   * @member {Boolean} IsModified
   */
  exports.prototype['IsModified'] = undefined;
  /**
   * Indicates the application status.
   * @member {String} IsModifiedReason
   * @default ''
   */
  exports.prototype['IsModifiedReason'] = '';
  /**
   * Indicates the application status.
   * @member {String} IsModifiedMessage
   * @default ''
   */
  exports.prototype['IsModifiedMessage'] = '';
  /**
   * Indicates the application consistency status.
   * @member {String} ConsistencyStatus
   * @default ''
   */
  exports.prototype['ConsistencyStatus'] = '';
  /**
   * Messages regarding the consistency status of the application.
   * @member {String} ConsistencyStatusMessages
   * @default ''
   */
  exports.prototype['ConsistencyStatusMessages'] = '';
  /**
   * Status of mobile apps in environment.
   * @member {Array.<module:model/MobileAppStatusInEnv>} MobileAppsStatus
   */
  exports.prototype['MobileAppsStatus'] = undefined;
  /**
   * Status of modules in environment.
   * @member {Array.<module:model/ModuleStatusInEnv>} ModuleStatusInEnvs
   */
  exports.prototype['ModuleStatusInEnvs'] = undefined;



  return exports;
}));


