/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeploymentMessage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeploymentMessage'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.DeploymentStatusDeploymentLogRecord = factory(root.LifetimeSdk.ApiClient, root.LifetimeSdk.DeploymentMessage);
  }
}(this, function(ApiClient, DeploymentMessage) {
  'use strict';




  /**
   * The DeploymentStatusDeploymentLogRecord model module.
   * @module model/DeploymentStatusDeploymentLogRecord
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>DeploymentStatusDeploymentLogRecord</code>.
   * 
   * @alias module:model/DeploymentStatusDeploymentLogRecord
   * @class
   * @param deploymentStatus {String} Status of the deployment. [saved | running | needs_user_intervention | aborted | aborting | finished_successful | finished_with_warnings | finished_with_errors]
   * @param deploymentLog {Array.<module:model/DeploymentMessage>} List of deployment messages.
   */
  var exports = function(deploymentStatus, deploymentLog) {
    var _this = this;

    _this['DeploymentStatus'] = deploymentStatus;
    _this['DeploymentLog'] = deploymentLog;
  };

  /**
   * Constructs a <code>DeploymentStatusDeploymentLogRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploymentStatusDeploymentLogRecord} obj Optional instance to populate.
   * @return {module:model/DeploymentStatusDeploymentLogRecord} The populated <code>DeploymentStatusDeploymentLogRecord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('DeploymentStatus')) {
        obj['DeploymentStatus'] = ApiClient.convertToType(data['DeploymentStatus'], 'String');
      }
      if (data.hasOwnProperty('DeploymentLog')) {
        obj['DeploymentLog'] = ApiClient.convertToType(data['DeploymentLog'], [DeploymentMessage]);
      }
    }
    return obj;
  }

  /**
   * Status of the deployment. [saved | running | needs_user_intervention | aborted | aborting | finished_successful | finished_with_warnings | finished_with_errors]
   * @member {String} DeploymentStatus
   * @default ''
   */
  exports.prototype['DeploymentStatus'] = '';
  /**
   * List of deployment messages.
   * @member {Array.<module:model/DeploymentMessage>} DeploymentLog
   */
  exports.prototype['DeploymentLog'] = undefined;



  return exports;
}));


