/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApplicationConflict', 'model/Deployment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApplicationConflict'), require('./Deployment'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.DeploymentApplicationConflictsRecord = factory(root.LifetimeSdk.ApiClient, root.LifetimeSdk.ApplicationConflict, root.LifetimeSdk.Deployment);
  }
}(this, function(ApiClient, ApplicationConflict, Deployment) {
  'use strict';




  /**
   * The DeploymentApplicationConflictsRecord model module.
   * @module model/DeploymentApplicationConflictsRecord
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>DeploymentApplicationConflictsRecord</code>.
   * 
   * @alias module:model/DeploymentApplicationConflictsRecord
   * @class
   * @param deployment {module:model/Deployment} 
   * @param applicationConflicts {Array.<module:model/ApplicationConflict>} List of conflicts between applications in the deployment.
   */
  var exports = function(deployment, applicationConflicts) {
    var _this = this;

    _this['Deployment'] = deployment;
    _this['ApplicationConflicts'] = applicationConflicts;
  };

  /**
   * Constructs a <code>DeploymentApplicationConflictsRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploymentApplicationConflictsRecord} obj Optional instance to populate.
   * @return {module:model/DeploymentApplicationConflictsRecord} The populated <code>DeploymentApplicationConflictsRecord</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Deployment')) {
        obj['Deployment'] = Deployment.constructFromObject(data['Deployment']);
      }
      if (data.hasOwnProperty('ApplicationConflicts')) {
        obj['ApplicationConflicts'] = ApiClient.convertToType(data['ApplicationConflicts'], [ApplicationConflict]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Deployment} Deployment
   */
  exports.prototype['Deployment'] = undefined;
  /**
   * List of conflicts between applications in the deployment.
   * @member {Array.<module:model/ApplicationConflict>} ApplicationConflicts
   */
  exports.prototype['ApplicationConflicts'] = undefined;



  return exports;
}));


