/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.DeploymentMessage = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DeploymentMessage model module.
   * @module model/DeploymentMessage
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>DeploymentMessage</code>.
   * Message from a deployment operation log.
   * @alias module:model/DeploymentMessage
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>DeploymentMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploymentMessage} obj Optional instance to populate.
   * @return {module:model/DeploymentMessage} The populated <code>DeploymentMessage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Instant')) {
        obj['Instant'] = ApiClient.convertToType(data['Instant'], 'Date');
      }
      if (data.hasOwnProperty('Message')) {
        obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
      }
    }
    return obj;
  }

  /**
   * Date and time when the message was logged.
   * @member {Date} Instant
   */
  exports.prototype['Instant'] = undefined;
  /**
   * Details of the message.
   * @member {String} Message
   * @default ''
   */
  exports.prototype['Message'] = '';



  return exports;
}));


