/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.MobileAppStatusInEnv = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MobileAppStatusInEnv model module.
   * @module model/MobileAppStatusInEnv
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>MobileAppStatusInEnv</code>.
   * Status of mobile application in a given environment.
   * @alias module:model/MobileAppStatusInEnv
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>MobileAppStatusInEnv</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MobileAppStatusInEnv} obj Optional instance to populate.
   * @return {module:model/MobileAppStatusInEnv} The populated <code>MobileAppStatusInEnv</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('EnvironmentKey')) {
        obj['EnvironmentKey'] = ApiClient.convertToType(data['EnvironmentKey'], 'String');
      }
      if (data.hasOwnProperty('NativePlatform')) {
        obj['NativePlatform'] = ApiClient.convertToType(data['NativePlatform'], 'String');
      }
      if (data.hasOwnProperty('VersionNumber')) {
        obj['VersionNumber'] = ApiClient.convertToType(data['VersionNumber'], 'String');
      }
      if (data.hasOwnProperty('HasBinaryAvailable')) {
        obj['HasBinaryAvailable'] = ApiClient.convertToType(data['HasBinaryAvailable'], 'Boolean');
      }
      if (data.hasOwnProperty('IsConfigured')) {
        obj['IsConfigured'] = ApiClient.convertToType(data['IsConfigured'], 'Boolean');
      }
      if (data.hasOwnProperty('IsConfigurationChanged')) {
        obj['IsConfigurationChanged'] = ApiClient.convertToType(data['IsConfigurationChanged'], 'Boolean');
      }
      if (data.hasOwnProperty('IsModified')) {
        obj['IsModified'] = ApiClient.convertToType(data['IsModified'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Environment unique identifier.
   * @member {String} EnvironmentKey
   * @default ''
   */
  exports.prototype['EnvironmentKey'] = '';
  /**
   * Name of native platform. [Android | iOS]
   * @member {String} NativePlatform
   * @default ''
   */
  exports.prototype['NativePlatform'] = '';
  /**
   * The version number, like for example 1.5.4, of the native build. It is used to be able to map the version to the version in the Andoid or iOS store.
   * @member {String} VersionNumber
   * @default ''
   */
  exports.prototype['VersionNumber'] = '';
  /**
   * True if the binary of the application is available for the current configuration.
   * @member {Boolean} HasBinaryAvailable
   */
  exports.prototype['HasBinaryAvailable'] = undefined;
  /**
   * True if the application is configured.
   * @member {Boolean} IsConfigured
   */
  exports.prototype['IsConfigured'] = undefined;
  /**
   * True if the configuration of the Mobile Application has changed in the environment.
   * @member {Boolean} IsConfigurationChanged
   */
  exports.prototype['IsConfigurationChanged'] = undefined;
  /**
   * True if the Native Hash of the Mobile Application does not match the one in the AppVersionNativeBuild baseline.
   * @member {Boolean} IsModified
   */
  exports.prototype['IsModified'] = undefined;



  return exports;
}));


