/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.MobileVersion = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MobileVersion model module.
   * @module model/MobileVersion
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>MobileVersion</code>.
   * A mobile version and its information.
   * @alias module:model/MobileVersion
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MobileVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MobileVersion} obj Optional instance to populate.
   * @return {module:model/MobileVersion} The populated <code>MobileVersion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('NativePlatform')) {
        obj['NativePlatform'] = ApiClient.convertToType(data['NativePlatform'], 'String');
      }
      if (data.hasOwnProperty('VersionNumber')) {
        obj['VersionNumber'] = ApiClient.convertToType(data['VersionNumber'], 'String');
      }
      if (data.hasOwnProperty('VersionDescription')) {
        obj['VersionDescription'] = ApiClient.convertToType(data['VersionDescription'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of native platform. [Android | iOS]
   * @member {String} NativePlatform
   * @default ''
   */
  exports.prototype['NativePlatform'] = '';
  /**
   * The version number, like for example 1.5.4, of the native build. It is used to be able to map the version to the version in the Andoid or iOS store.
   * @member {String} VersionNumber
   * @default ''
   */
  exports.prototype['VersionNumber'] = '';
  /**
   * The description of the mobile version.
   * @member {String} VersionDescription
   * @default ''
   */
  exports.prototype['VersionDescription'] = '';



  return exports;
}));


