/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ModuleStatusInEnv = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModuleStatusInEnv model module.
   * @module model/ModuleStatusInEnv
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ModuleStatusInEnv</code>.
   * Status of module in a given environment.
   * @alias module:model/ModuleStatusInEnv
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>ModuleStatusInEnv</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModuleStatusInEnv} obj Optional instance to populate.
   * @return {module:model/ModuleStatusInEnv} The populated <code>ModuleStatusInEnv</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ApplicationKey')) {
        obj['ApplicationKey'] = ApiClient.convertToType(data['ApplicationKey'], 'String');
      }
      if (data.hasOwnProperty('EnvironmentKey')) {
        obj['EnvironmentKey'] = ApiClient.convertToType(data['EnvironmentKey'], 'String');
      }
      if (data.hasOwnProperty('ModuleVersionKey')) {
        obj['ModuleVersionKey'] = ApiClient.convertToType(data['ModuleVersionKey'], 'String');
      }
      if (data.hasOwnProperty('ConsistencyStatus')) {
        obj['ConsistencyStatus'] = ApiClient.convertToType(data['ConsistencyStatus'], 'String');
      }
      if (data.hasOwnProperty('ConsistencyStatusMessages')) {
        obj['ConsistencyStatusMessages'] = ApiClient.convertToType(data['ConsistencyStatusMessages'], 'String');
      }
    }
    return obj;
  }

  /**
   * Application unique identifier.
   * @member {String} ApplicationKey
   * @default ''
   */
  exports.prototype['ApplicationKey'] = '';
  /**
   * Environment unique identifier.
   * @member {String} EnvironmentKey
   * @default ''
   */
  exports.prototype['EnvironmentKey'] = '';
  /**
   * Module version unique identifier.
   * @member {String} ModuleVersionKey
   * @default ''
   */
  exports.prototype['ModuleVersionKey'] = '';
  /**
   * Indicates the module consistency status.
   * @member {String} ConsistencyStatus
   * @default ''
   */
  exports.prototype['ConsistencyStatus'] = '';
  /**
   * Messages regarding the consistency status of the module.
   * @member {String} ConsistencyStatusMessages
   * @default ''
   */
  exports.prototype['ConsistencyStatusMessages'] = '';



  return exports;
}));


