/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LifetimeSdk) {
      root.LifetimeSdk = {};
    }
    root.LifetimeSdk.ModuleConflict = factory(root.LifetimeSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ModuleConflict model module.
   * @module model/ModuleConflict
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>ModuleConflict</code>.
   * A module conflict.
   * @alias module:model/ModuleConflict
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ModuleConflict</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModuleConflict} obj Optional instance to populate.
   * @return {module:model/ModuleConflict} The populated <code>ModuleConflict</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ProducerModuleKey')) {
        obj['ProducerModuleKey'] = ApiClient.convertToType(data['ProducerModuleKey'], 'String');
      }
      if (data.hasOwnProperty('ConsumerModuleKey')) {
        obj['ConsumerModuleKey'] = ApiClient.convertToType(data['ConsumerModuleKey'], 'String');
      }
      if (data.hasOwnProperty('TotalRequiredElements')) {
        obj['TotalRequiredElements'] = ApiClient.convertToType(data['TotalRequiredElements'], 'Number');
      }
      if (data.hasOwnProperty('ConflictType')) {
        obj['ConflictType'] = ApiClient.convertToType(data['ConflictType'], 'String');
      }
    }
    return obj;
  }

  /**
   * Producer Module unique identifier.
   * @member {String} ProducerModuleKey
   * @default ''
   */
  exports.prototype['ProducerModuleKey'] = '';
  /**
   * Consumer Module unique identifier.
   * @member {String} ConsumerModuleKey
   * @default ''
   */
  exports.prototype['ConsumerModuleKey'] = '';
  /**
   * Total number of required elements.
   * @member {Number} TotalRequiredElements
   */
  exports.prototype['TotalRequiredElements'] = undefined;
  /**
   * Type of conflict. [Producer Module Missing|Producer Element Missing|Producer Element Incompatible|Consumer Module Outdated|Newer Producer Module Available|IncompatiblePlatformServer|ConsumerModuleMoved|ProducerModuleMoved|NameColision]
   * @member {String} ConflictType
   * @default ''
   */
  exports.prototype['ConflictType'] = '';



  return exports;
}));


