/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AppStatusInEnv', 'model/Application', 'model/ApplicationConflict', 'model/ApplicationOperation', 'model/ApplicationVersion', 'model/ApplicationVersionCreate', 'model/ApplicationVersionKeyRecord', 'model/Deployment', 'model/DeploymentApplicationConflictsRecord', 'model/DeploymentMessage', 'model/DeploymentStatusDeploymentLogRecord', 'model/DownloadLink', 'model/Environment', 'model/MobileAppStatusInEnv', 'model/MobileVersion', 'model/Module', 'model/ModuleConflict', 'model/ModuleElement', 'model/ModuleStatusInEnv', 'model/ModuleVersion', 'model/NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord', 'api/V1Api'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/AppStatusInEnv'), require('./model/Application'), require('./model/ApplicationConflict'), require('./model/ApplicationOperation'), require('./model/ApplicationVersion'), require('./model/ApplicationVersionCreate'), require('./model/ApplicationVersionKeyRecord'), require('./model/Deployment'), require('./model/DeploymentApplicationConflictsRecord'), require('./model/DeploymentMessage'), require('./model/DeploymentStatusDeploymentLogRecord'), require('./model/DownloadLink'), require('./model/Environment'), require('./model/MobileAppStatusInEnv'), require('./model/MobileVersion'), require('./model/Module'), require('./model/ModuleConflict'), require('./model/ModuleElement'), require('./model/ModuleStatusInEnv'), require('./model/ModuleVersion'), require('./model/NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord'), require('./api/V1Api'));
  }
}(function(ApiClient, AppStatusInEnv, Application, ApplicationConflict, ApplicationOperation, ApplicationVersion, ApplicationVersionCreate, ApplicationVersionKeyRecord, Deployment, DeploymentApplicationConflictsRecord, DeploymentMessage, DeploymentStatusDeploymentLogRecord, DownloadLink, Environment, MobileAppStatusInEnv, MobileVersion, Module, ModuleConflict, ModuleElement, ModuleStatusInEnv, ModuleVersion, NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord, V1Api) {
  'use strict';

  /**
   * Client library of Outsystems Lifetime.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var LifetimeSdk = require('index'); // See note below*.
   * var xxxSvc = new LifetimeSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new LifetimeSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new LifetimeSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new LifetimeSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.0.1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The AppStatusInEnv model constructor.
     * @property {module:model/AppStatusInEnv}
     */
    AppStatusInEnv: AppStatusInEnv,
    /**
     * The Application model constructor.
     * @property {module:model/Application}
     */
    Application: Application,
    /**
     * The ApplicationConflict model constructor.
     * @property {module:model/ApplicationConflict}
     */
    ApplicationConflict: ApplicationConflict,
    /**
     * The ApplicationOperation model constructor.
     * @property {module:model/ApplicationOperation}
     */
    ApplicationOperation: ApplicationOperation,
    /**
     * The ApplicationVersion model constructor.
     * @property {module:model/ApplicationVersion}
     */
    ApplicationVersion: ApplicationVersion,
    /**
     * The ApplicationVersionCreate model constructor.
     * @property {module:model/ApplicationVersionCreate}
     */
    ApplicationVersionCreate: ApplicationVersionCreate,
    /**
     * The ApplicationVersionKeyRecord model constructor.
     * @property {module:model/ApplicationVersionKeyRecord}
     */
    ApplicationVersionKeyRecord: ApplicationVersionKeyRecord,
    /**
     * The Deployment model constructor.
     * @property {module:model/Deployment}
     */
    Deployment: Deployment,
    /**
     * The DeploymentApplicationConflictsRecord model constructor.
     * @property {module:model/DeploymentApplicationConflictsRecord}
     */
    DeploymentApplicationConflictsRecord: DeploymentApplicationConflictsRecord,
    /**
     * The DeploymentMessage model constructor.
     * @property {module:model/DeploymentMessage}
     */
    DeploymentMessage: DeploymentMessage,
    /**
     * The DeploymentStatusDeploymentLogRecord model constructor.
     * @property {module:model/DeploymentStatusDeploymentLogRecord}
     */
    DeploymentStatusDeploymentLogRecord: DeploymentStatusDeploymentLogRecord,
    /**
     * The DownloadLink model constructor.
     * @property {module:model/DownloadLink}
     */
    DownloadLink: DownloadLink,
    /**
     * The Environment model constructor.
     * @property {module:model/Environment}
     */
    Environment: Environment,
    /**
     * The MobileAppStatusInEnv model constructor.
     * @property {module:model/MobileAppStatusInEnv}
     */
    MobileAppStatusInEnv: MobileAppStatusInEnv,
    /**
     * The MobileVersion model constructor.
     * @property {module:model/MobileVersion}
     */
    MobileVersion: MobileVersion,
    /**
     * The Module model constructor.
     * @property {module:model/Module}
     */
    Module: Module,
    /**
     * The ModuleConflict model constructor.
     * @property {module:model/ModuleConflict}
     */
    ModuleConflict: ModuleConflict,
    /**
     * The ModuleElement model constructor.
     * @property {module:model/ModuleElement}
     */
    ModuleElement: ModuleElement,
    /**
     * The ModuleStatusInEnv model constructor.
     * @property {module:model/ModuleStatusInEnv}
     */
    ModuleStatusInEnv: ModuleStatusInEnv,
    /**
     * The ModuleVersion model constructor.
     * @property {module:model/ModuleVersion}
     */
    ModuleVersion: ModuleVersion,
    /**
     * The NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord model constructor.
     * @property {module:model/NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord}
     */
    NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord: NotesSourceEnvironmentKeyTargetEnvironmentKeyApplicationVersionKeysRecord,
    /**
     * The V1Api service constructor.
     * @property {module:api/V1Api}
     */
    V1Api: V1Api
  };

  return exports;
}));
