/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LifetimeSdk);
  }
}(this, function(expect, LifetimeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LifetimeSdk.ApplicationVersionCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApplicationVersionCreate', function() {
    it('should create an instance of ApplicationVersionCreate', function() {
      // uncomment below and update the code to test ApplicationVersionCreate
      //var instane = new LifetimeSdk.ApplicationVersionCreate();
      //expect(instance).to.be.a(LifetimeSdk.ApplicationVersionCreate);
    });

    it('should have the property changeLog (base name: "ChangeLog")', function() {
      // uncomment below and update the code to test the property changeLog
      //var instane = new LifetimeSdk.ApplicationVersionCreate();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "Version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new LifetimeSdk.ApplicationVersionCreate();
      //expect(instance).to.be();
    });

    it('should have the property mobileVersions (base name: "MobileVersions")', function() {
      // uncomment below and update the code to test the property mobileVersions
      //var instane = new LifetimeSdk.ApplicationVersionCreate();
      //expect(instance).to.be();
    });

    it('should have the property moduleVersionKeys (base name: "ModuleVersionKeys")', function() {
      // uncomment below and update the code to test the property moduleVersionKeys
      //var instane = new LifetimeSdk.ApplicationVersionCreate();
      //expect(instance).to.be();
    });

  });

}));
