/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LifetimeSdk);
  }
}(this, function(expect, LifetimeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LifetimeSdk.AppStatusInEnv();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AppStatusInEnv', function() {
    it('should create an instance of AppStatusInEnv', function() {
      // uncomment below and update the code to test AppStatusInEnv
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be.a(LifetimeSdk.AppStatusInEnv);
    });

    it('should have the property environmentKey (base name: "EnvironmentKey")', function() {
      // uncomment below and update the code to test the property environmentKey
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property baseApplicationVersionKey (base name: "BaseApplicationVersionKey")', function() {
      // uncomment below and update the code to test the property baseApplicationVersionKey
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isModified (base name: "IsModified")', function() {
      // uncomment below and update the code to test the property isModified
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isModifiedReason (base name: "IsModifiedReason")', function() {
      // uncomment below and update the code to test the property isModifiedReason
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isModifiedMessage (base name: "IsModifiedMessage")', function() {
      // uncomment below and update the code to test the property isModifiedMessage
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property consistencyStatus (base name: "ConsistencyStatus")', function() {
      // uncomment below and update the code to test the property consistencyStatus
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property consistencyStatusMessages (base name: "ConsistencyStatusMessages")', function() {
      // uncomment below and update the code to test the property consistencyStatusMessages
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property mobileAppsStatus (base name: "MobileAppsStatus")', function() {
      // uncomment below and update the code to test the property mobileAppsStatus
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property moduleStatusInEnvs (base name: "ModuleStatusInEnvs")', function() {
      // uncomment below and update the code to test the property moduleStatusInEnvs
      //var instane = new LifetimeSdk.AppStatusInEnv();
      //expect(instance).to.be();
    });

  });

}));
