/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LifetimeSdk);
  }
}(this, function(expect, LifetimeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LifetimeSdk.Environment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Environment', function() {
    it('should create an instance of Environment', function() {
      // uncomment below and update the code to test Environment
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be.a(LifetimeSdk.Environment);
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property oSVersion (base name: "OSVersion")', function() {
      // uncomment below and update the code to test the property oSVersion
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "Order")', function() {
      // uncomment below and update the code to test the property order
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property hostName (base name: "HostName")', function() {
      // uncomment below and update the code to test the property hostName
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property useHTTPS (base name: "UseHTTPS")', function() {
      // uncomment below and update the code to test the property useHTTPS
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property environmentType (base name: "EnvironmentType")', function() {
      // uncomment below and update the code to test the property environmentType
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property numberOfFrontEnds (base name: "NumberOfFrontEnds")', function() {
      // uncomment below and update the code to test the property numberOfFrontEnds
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property applicationServerType (base name: "ApplicationServerType")', function() {
      // uncomment below and update the code to test the property applicationServerType
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property applicationServer (base name: "ApplicationServer")', function() {
      // uncomment below and update the code to test the property applicationServer
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property databaseProvider (base name: "DatabaseProvider")', function() {
      // uncomment below and update the code to test the property databaseProvider
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

    it('should have the property isCloudEnvironment (base name: "IsCloudEnvironment")', function() {
      // uncomment below and update the code to test the property isCloudEnvironment
      //var instane = new LifetimeSdk.Environment();
      //expect(instance).to.be();
    });

  });

}));
