/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LifetimeSdk);
  }
}(this, function(expect, LifetimeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LifetimeSdk.MobileAppStatusInEnv();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MobileAppStatusInEnv', function() {
    it('should create an instance of MobileAppStatusInEnv', function() {
      // uncomment below and update the code to test MobileAppStatusInEnv
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be.a(LifetimeSdk.MobileAppStatusInEnv);
    });

    it('should have the property environmentKey (base name: "EnvironmentKey")', function() {
      // uncomment below and update the code to test the property environmentKey
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property nativePlatform (base name: "NativePlatform")', function() {
      // uncomment below and update the code to test the property nativePlatform
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property versionNumber (base name: "VersionNumber")', function() {
      // uncomment below and update the code to test the property versionNumber
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property hasBinaryAvailable (base name: "HasBinaryAvailable")', function() {
      // uncomment below and update the code to test the property hasBinaryAvailable
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isConfigured (base name: "IsConfigured")', function() {
      // uncomment below and update the code to test the property isConfigured
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isConfigurationChanged (base name: "IsConfigurationChanged")', function() {
      // uncomment below and update the code to test the property isConfigurationChanged
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

    it('should have the property isModified (base name: "IsModified")', function() {
      // uncomment below and update the code to test the property isModified
      //var instane = new LifetimeSdk.MobileAppStatusInEnv();
      //expect(instance).to.be();
    });

  });

}));
