/**
 * v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LifetimeSdk);
  }
}(this, function(expect, LifetimeSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LifetimeSdk.ModuleVersion();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ModuleVersion', function() {
    it('should create an instance of ModuleVersion', function() {
      // uncomment below and update the code to test ModuleVersion
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be.a(LifetimeSdk.ModuleVersion);
    });

    it('should have the property key (base name: "Key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property moduleKey (base name: "ModuleKey")', function() {
      // uncomment below and update the code to test the property moduleKey
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "CreatedOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "CreatedBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property createdByUsername (base name: "CreatedByUsername")', function() {
      // uncomment below and update the code to test the property createdByUsername
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property generalHash (base name: "GeneralHash")', function() {
      // uncomment below and update the code to test the property generalHash
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property directUpgradeFromHash (base name: "DirectUpgradeFromHash")', function() {
      // uncomment below and update the code to test the property directUpgradeFromHash
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property publicElements (base name: "PublicElements")', function() {
      // uncomment below and update the code to test the property publicElements
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

    it('should have the property consumedElements (base name: "ConsumedElements")', function() {
      // uncomment below and update the code to test the property consumedElements
      //var instane = new LifetimeSdk.ModuleVersion();
      //expect(instance).to.be();
    });

  });

}));
